### ISSUE TITLE
[FR]: Adding support for 'Mehrmaid' diagrams

### ISSUE THREAD

**Issue by avirosso** [gitcpy/obsidian-diagram-pop#4]
Thanks for this great plugin!

A small request: Would it be possible to support also the (better) 'mehrmaid' diagrams?

https://github.com/huterguier/obsidian-mehrmaid

Thanks in advance!

**Comment by gitcpy** [comment]
https://github.com/gitcpy/diagram-zoom-drag/issues
This is the plulgin satisfied your fr.
I will add your fr in obsidian-mermaid-pop in one  version of future. 
Hope not long

**Comment by avirosso** [comment]
Thanks for adding the 'mehrmaid'-support in the near future!

(I've testet the 'diagram zoom drag' plugin but it doesn't fit my needs - i.e. it has a black background in fullscreen, so the arrows aren't visible any more ...)

**Comment by gitcpy** [comment]
In 'diagram zoom drag' , the arrows aren visible. If you have any problem, feel free to leave message with pic better.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-mermaid-pop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月25日(星期三) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] [FR]: Adding support for 'Mehrmaid' diagrams (Issue #4)






Thanks for adding the 'mehrmaid'-support in the near future!

(I've testet the 'diagram zoom drag' plugin but it doesn't fit my needs - i.e. it has a black background in fullscreen, so the arrows aren't visible any more ...)

**Comment by avirosso** [comment]
I opened a issue for 'diagram-zoom-drag':

https://github.com/gitcpy/diagram-zoom-drag/issues/25

(Nevertheless the 'mehrmaid' support in mermaid popup plugin would be great!)

**Comment by gitcpy** [comment]
feat: added.
Follow the steps:
![扩展使用1](https://github.com/user-attachments/assets/db507d1e-aef0-495f-a778-b367d7f5d23a)
![扩展使用2-选择class](https://github.com/user-attachments/assets/06c31eee-284d-48b4-a4b3-07105d6676ab)
![扩展使用3-设置扩展class name - 2](https://github.com/user-attachments/assets/18024288-9320-4b87-9bfb-57fbf1698a7c)
![扩展使用3-设置扩展class name](https://github.com/user-attachments/assets/67587009-c7cd-4482-a191-268dc5bcab1c)
![扩展使用4-重新打开文件-点击右下角按钮 或者 ctrl and left](https://github.com/user-attachments/assets/6d0a6066-e0f0-4a6c-9196-4e701ce94ac6)
![扩展使用5-弹窗效果](https://github.com/user-attachments/assets/3503e36d-c832-4cb2-b53c-57a41d2d669d)

**Comment by avirosso** [comment]
Great! Thanks for the mehrmaid-support and the perfect explanation!

**Comment by gitcpy** [comment]
> Great! Thanks for the mehrmaid-support and the perfect explanation!

I renamed the plugin. 
It is auditing. And Users couldn't get it unless it passes.
And we could get it from BRAT for the moment.
Here is the url, https://github.com/gitcpy/obsidian-diagram-pop.
